mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('pmos/', include('pmos.urls')),
]

mysite/pmos/urls.py
from django.urls import path
from . import views

app_name='pmos'

urlpatterns = [
    path('monitor/', views.monitor, name='monitor'),
    path('memo/', views.memo, name='memo'),
    path('memo_add/', views.memo_add, name='memo_add'),
    path('memo_edit/<int:memocond_id>/', views.memo_edit, name='memo_edit'),
    path('memo_delete/<int:memocond_id>/', views.memo_delete, name='memo_delete'),
    path('household/', views.household, name='household'),
    path('household_add/', views.household_add, name='household_add'),
    path('household_main/', views.household_main, name='household_main'),
    path('household_edit/<int:housecond_id>/', views.household_edit, name='household_edit'),
    path('household_delete/<int:housecond_id>/', views.household_delete, name='household_delete'),
    path('room_add/', views.room_add, name='room_add')
]

mysite/pmos/models.py
from django.db import models
#import datetime
from django.utils import timezone

class Roomcond(models.Model):
    temp = models.IntegerField(default=0)
    humi = models.IntegerField(default=0)
    motion = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "temp : {}, humi : {}, motion : {}".format(self.temp,self.humi,self.motion)

class Memocond(models.Model):
    text = models.CharField(max_length = 100)
    lat = models.FloatField(max_length = 100, default=37.5400399)
    lon = models.FloatField(max_length = 100, default=127.09341909999999)
    locate = models.CharField(max_length = 50, default='aa')
    person = models.CharField(max_length = 50, default='cc')
    temp = models.IntegerField(default=30)
    humi = models. IntegerField(default=30)
    weat = models.CharField(max_length = 20, default='bb')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text, self.date

class Housecond(models.Model):
    expense = models.IntegerField()
    person = models.CharField(max_length=20)
    use = models.CharField(max_length=20)
    comment = models.CharField(max_length=50, default='-')
    date = models.DateTimeField(auto_now_add=True)

class Balance(models.Model):
    new_balance = models.IntegerField(default=0)

mysite/pmos/forms.py
import datetime
from django import forms
from .models import Roomcond, Memocond, Housecond

class HouseForm(forms.ModelForm):
    class Meta:
        model = Housecond
        fields=('expense', 'use', 'comment')

        #balance = forms.IntegerField(initial = prev_housecond.balance)
        #expense = forms.IntegerField()
        #person = forms.CharField()
        #use = forms.CharField()
        #comment = forms.CharField()
        #date = forms.DateField(initial=datetime.date.today)

class MemoForm(forms.ModelForm):
    class Meta:
        model = Memocond
        fields=('text', 'lat', 'lon',)
        widgets = {
            'text': forms.Textarea(attrs={'cols': 45, 'rows': 8}),
        }

class RoomForm(forms.ModelForm):
    class Meta:
        model = Roomcond
        fields=('temp', 'humi', 'motion',)

mysite/pmos/views.py
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect

import requests, json

from django.http import HttpResponseRedirect, HttpResponse

from django.urls import reverse

from pmos.models import Roomcond, Memocond, Housecond, Balance

from .forms import RoomForm, HouseForm, MemoForm

from django.contrib.auth import get_user

from django.core.paginator import Paginator

#from django.utils import timezone

import datetime

from django.views.decorators.csrf import csrf_exempt

# Create your views here.

headers = {'Authorization':'KakaoAK ef023e151052064467c31652f247eae2'}

def monitor(request):
    roomcond_list = Roomcond.objects.all().order_by('-id')[:20]
    latest_roomcond = roomcond_list[0]
    return render(request, 'pmos/monitor.html', {'latest_roomcond':latest_roomcond})

def memo(request):
    current_user=get_user(request)
    memoconds = Memocond.objects
    memocond_list = Memocond.objects.filter(person=current_user.first_name).order_by('-date')
    paginator = Paginator(memocond_list, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    #return render(request, 'pmos/memo.html', {'memocond_list':memocond_list})
    return render(request, 'pmos/memo.html', {'memoconds':memoconds, 'posts':posts})

def memo_add(request):
    if request.method == "POST":
        current_user=get_user(request)
        form = MemoForm(request.POST, request.FILES)
        if form.is_valid():
            memo = form.save(commit=False)
            url = 'http://api.openweathermap.org/data/2.5/weather?lat={}&lon={}&appid=19c6ecde75f00332ef1416854a8fd1be'.format(memo.lat, memo.lon)
            url2 = 'https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={}&y={}&input_coord=WGS84'.format(memo.lon, memo.lat)
            city_name = requests.get(url2, headers=headers).json()
            city_weather = requests.get(url).json()
            memo.person = current_user.first_name
            memo.temp = round(city_weather['main']['temp']/10)
            memo.humi = city_weather['main']['humidity']
            memo.locate = city_name['documents'][0]['address_name']
            memo.weat = city_weather['weather'][0]['description']
            memo.save()
            return HttpResponseRedirect(reverse('pmos:memo')) # Redirect after POST
    else:
        form = MemoForm()
        return render(request, 'pmos/memo_add.html', {'form':form})

def memo_edit(request, memocond_id):
    memo = Memocond.objects.get(id=memocond_id)
    if request.method == "POST":
        current_user=get_user(request)
        form = MemoForm(request.POST, request.FILES)
        if form.is_valid():
            memo.text = form.cleaned_data['text']
            memo.lat = form.cleaned_data['lat']
            memo.lon = form.cleaned_data['lon']
            url = 'http://api.openweathermap.org/data/2.5/weather?lat={}&lon={}&appid=19c6ecde75f00332ef1416854a8fd1be'.format(memo.lat, memo.lon)
            url2 = 'https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={}&y={}&input_coord=WGS84'.format(memo.lon, memo.lat)
            city_name = requests.get(url2, headers=headers).json()
            city_weather = requests.get(url).json()
            memo.person = current_user.first_name
            memo.temp = round(city_weather['main']['temp']/10)
            memo.humi = city_weather['main']['humidity']
            memo.locate = city_name['documents'][0]['address_name']
            memo.weat = city_weather['weather'][0]['description']
            memo.save()
            return HttpResponseRedirect(reverse('pmos:memo')) # Redirect after POST
    else:
        form = MemoForm()
        return render(request, 'pmos/memo_edit.html', {'form':form})

def memo_delete(request, memocond_id):
    obj = Memocond.objects.get(pk=memocond_id)
    obj.delete()
    return redirect('/pmos/memo')

def household_main(request):
    household_balance = Balance.objects.get(pk=1)
    household_list = Housecond.objects.all()
    for housecond in household_list:
        if housecond.use == '이체':
            household_balance.new_balance += housecond.expense
        else :
            household_balance.new_balance -= housecond.expense
    return render(request, 'pmos/household_main.html', {'household_balance':household_balance})

def household(request):
    household_list = Housecond.objects.filter(date__month=datetime.date.today().month)
    return render(request, 'pmos/household.html', {'household_list':household_list})

def household_add(request):
    if request.method == "POST":
        current_user=get_user(request)
        form = HouseForm(request.POST, request.FILES)
        if form.is_valid():
            house = form.save(commit=False)
            house.person = current_user.first_name
            house.save()
            return HttpResponseRedirect(reverse('pmos:household_main')) # Redirect after POST
    else:
        form = HouseForm()
        return render(request, 'pmos/household_add.html', {'form':form})

def household_edit(request, housecond_id):
    house = Housecond.objects.get(id=housecond_id)
    if request.method=="POST":
        current_user=get_user(request)
        form = HouseForm(request.POST, request.FILES)
        if form.is_valid():
            house.expense = form.cleaned_data['expense']
            house.person = current_user.first_name
            house.use = form.cleaned_data['use']
            house.comment = form.cleaned_data['comment']
            house.save()
            return HttpResponseRedirect(reverse('pmos:household_main'))
    else:
        form = HouseForm()
        return render(request, 'pmos/household_edit.html', {'form':form})

def household_delete(request, housecond_id):
    obj = Housecond.objects.get(pk=housecond_id)
    obj.delete()
    return redirect('/pmos/household_main')

@csrf_exempt
def room_add(request):
    if request.method == 'POST':
        received_json_data=json.loads(request.body)
        new_roomcond = Roomcond(temp = received_json_data['temp'], humi = received_json_data['humi'])
        new_roomcond.save()
        return HttpResponse('ok')

mysite/pmos/templates/pmos/household.html
{% extends 'base.html' %}
{% block title %}Household List{% endblock %}
{% block content %}
<h1 class="mainh2"><a href="{% url 'pmos:household_main' %}">가계부 목록</a></h1>
<table class="tablehouse" align="center">
  <thead>
    <th>날짜</th><th>금액</th><th>용도</th><th>작성자</th><th>비고</th>
  </thead>
  <tbody>
    {% for Housecond in household_list %}
    <tr>
      <td>{{Housecond.date | date:"Y-m-d" }}</td><td>{{Housecond.expense}}</td><td>{{Housecond.use}}</td><td>{{Housecond.person}}</td><td>{{Housecond.comment}}</td>
      <td><button class="button3" type="button" onclick="location.href='{% url 'pmos:household_edit' Housecond.id %}'">수정</button></td>
      <td><button class="button3" type="button" onclick="location.href='{% url 'pmos:household_delete' Housecond.id %}'">삭제</button></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
  <br>
  <button class="button1" type="button" onclick="location.href='{% url 'pmos:household_add' %}'">가계부 추가</button></td>
{% endblock %}

mysite/pmos/templates/pmos/household_add.html
{% extends 'base.html' %}
{% block title %}Household Add{% endblock %}
{% block content %}
<h1 class="mainh1">가계부 추가</h1>
<form action="{% url 'pmos:household_add' %}" method="post">
{% csrf_token %}
<p><label for="id_expense"> 비용 : </label>{{ form.expense }}</p>
<p><label for="id_comment"> 비고 : </label>{{ form.comment }}</p>
<!--<p>
  <label for="id_person1"></label> person : 박형모 <input id="id_person1" type="radio" name="person" value="박형모">
  <label for="id_person2"></label> 백승빈 <input id="id_person2" type="radio" name="person" value="백승빈">
  <label for="id_person3"></label> 유형일 <input id="id_person3" type="radio" name="person" value="조현장">
  <label for="id_person4"></label> 조현장 <input id="id_person4" type="radio" name="person" value="유형일">
</p>-->
<p>
  <label for="id_use1">이체</label><input id="id_use1" type="radio" name="use" value="이체">
  <label for="id_use2">식비</label><input id="id_use2" type="radio" name="use" value="식비">
  <label for="id_use3">공공재</label><input id="id_use3" type="radio" name="use" value="공공재">
  <label for="id_use4">공과금</label><input id="id_use4" type="radio" name="use" value="공과금">
</p>
<button type="submit" class="button2">추가</button>
</form>
{% endblock %}

mysite/pmos/templates/pmos/household_edit.html
{% extends 'base.html' %}
{% block title %}Household Add{% endblock %}
{% block content %}
    <h1 class="mainh1">가계부 수정</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p><label for="id_expense"> 비용 : </label>{{ form.expense }}</p>
        <p><label for="id_comment"> 비고 : </label>{{ form.comment }}</p>
        <!--<p>
          <label for="id_person1"></label> person : 박형모 <input id="id_person1" type="radio" name="person" value="박형모">
          <label for="id_person2"></label> 백승빈 <input id="id_person2" type="radio" name="person" value="백승빈">
          <label for="id_person3"></label> 유형일 <input id="id_person3" type="radio" name="person" value="조현장">
          <label for="id_person4"></label> 조현장 <input id="id_person4" type="radio" name="person" value="유형일">
        </p>-->
        <p>
          <label for="id_use1">이체</label><input id="id_use1" type="radio" name="use" value="이체">
          <label for="id_use2">식비</label><input id="id_use2" type="radio" name="use" value="식비">
          <label for="id_use3">공공재</label><input id="id_use3" type="radio" name="use" value="공공재">
          <label for="id_use4">공과금</label><input id="id_use4" type="radio" name="use" value="공과금">
        </p>
        <br>
        <button type="submit" class="button2">수정</button>
    </form>
{% endblock %}

mysite/pmos/templates/pmos/household_main.html
{% extends 'base.html' %}
{% block title %}Household Main{% endblock %}
{% block content %}
<h1 class="mainh1"><a href="{% url 'home' %}">가계부 잔고 확인</a></h1>
<h2>잔고 : {{ household_balance.new_balance }}원</h2>
  <button class="button2" type="button" onclick="location.href='{% url 'pmos:household_add' %}'">추가</button>
  <button class="button2" type="button" onclick="location.href='{% url 'pmos:household' %}'">목록</button>
  {% endblock %}

mysite/pmos/templates/pmos/memo.html
{% extends 'base.html' %}
{% block title %}Memo List{% endblock %}
{% block content %}
    <!--<h1>My Memo</h1>
      {% for Memocond in memocond_list %}
      <table class="tablememo" align="center" border="1">
        <tbody>
          <tr>
            <td colspan="4">{{ Memocond.text }}</td>
          </tr>
          <tr>
            <td>온도 : {{ Memocond.temp }}°C</td>
            <td>습도 : {{ Memocond.humi }}%</td>
            <td colspan="2">{{ Memocond.locate }}</td>
          </tr>
         <tr>
            <td colspan="2">날씨 : {{  Memocond.weat }}</td>
            <td colspan="2">{{ Memocond.date }}</td>
          </tr>
          </tbody>
        </table>
        <button class="button2" type="button" onclick="location.href='{% url 'pmos:memo_edit' Memocond.id %}'">수정</button>
        <button class="button2" type="button" onclick="location.href='{% url 'pmos:memo_delete' Memocond.id %}'">삭제</button>
        <br><br>
        {% endfor %}
        <button class="button1" type="button" onclick="location.href='{% url 'pmos:memo_add' %}'">메모 추가</button>-->

        <h1 class="mainh1"><a href="{% url 'home' %}">나의 메모</a></h1>
          {% for Memocond in posts %}
          <table class="tablememo" align="center" border="1">
            <tbody>
              <tr>
                <td colspan="4">{{ Memocond.text }}</td>
              </tr>
              <tr>
                <td>온도 : {{ Memocond.temp }}°C</td>
                <td>습도 : {{ Memocond.humi }}%</td>
                <td colspan="2">{{ Memocond.locate }}</td>
              </tr>
             <tr>
                <td colspan="2">날씨 : {{  Memocond.weat }}</td>
                <td colspan="2">{{ Memocond.date | date:"Y-m-d h:i:s"}}</td>
              </tr>
              </tbody>
            </table>
            <button class="button2" type="button" onclick="location.href='{% url 'pmos:memo_edit' Memocond.id %}'">수정</button>
            <button class="button2" type="button" onclick="location.href='{% url 'pmos:memo_delete' Memocond.id %}'">삭제</button>
            <br><br>
            {% endfor %}
            <button class="button1" type="button" onclick="location.href='{% url 'pmos:memo_add' %}'">메모 추가</button>
            <br>
            <br>
            {% if posts.has_previous %}
            <a href="?page=1">처음</a>&nbsp;&nbsp;
            <a href="?page={{posts.has_previous_page_number}}">이전</a>
            {% endif %}&nbsp;&nbsp;
            <span>{{posts.number}}</span>
            <span>/</span>
            <span>{{ posts.paginator.num_pages }}</span>
            {% if posts.has_next %}&nbsp;&nbsp;
            <a href="?page={{ posts.next_page_number }}">다음</a>&nbsp;&nbsp;
            <a href="?page={{ posts.paginator.num_pages }}">끝</a>
            {% endif %}
{% endblock %}

mysite/pmos/templates/pmos/memo_add.html
{% extends 'base.html' %}
{% block head %}
<script type="text/JavaScript">
  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        document.getElementById('lat').value=position.coords.latitude;
        document.getElementById('lon').value=position.coords.longitude;
      }, function(error) {
        alert('Error occurred. Error code: ' + error.code);
      },
      {timeout: 30000, enableHighAccuracy: true, maximumAge: 75000});}
    else {
      alert('GPS를 지원하지 않습니다');
    }
  }
</script>
{% endblock %}
{% block title %}Memo Edit{% endblock %}
{% block content %}
    <h1> 메모 추가 </h1>
    <form action="{% url 'pmos:memo_add' %}" method="post">
    {% csrf_token %}
    {{ form.text }}
    <br>
    <br>
    <label for="lat">lat : </label><input type="number" class="numbers" step=any name="lat" id="lat"/>
    &nbsp;&nbsp;&nbsp;
    <label for="lon">lon : </label><input type="number" class="numbers" step=any name="lon" id="lon"/><br>
    <br>
    <!--<button type="button" class="button2" onClick = "getLocation()" value = "현재위치등록""/>-->
    <!--<button type="button" name="button"></button>-->
    <!--<input class="button2" type = "button" onClick = "getLocation()" value = "현재위치등록" />-->
    <button type="button" class="button2" onClick="getLocation()">위치등록</button>
    &nbsp;&nbsp;&nbsp;
    <button type="submit" class="button2">추가</button>
    </form>
{% endblock %}

mysite/pmos/templates/pmos/memo_edit.html
{% extends 'base.html' %}
{% block head %}
<script type="text/JavaScript">
  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        document.getElementById('lat').value=position.coords.latitude;
        document.getElementById('lon').value=position.coords.longitude;
      }, function(error) {
        alert('Error occurred. Error code: ' + error.code);
      },
      {timeout: 30000, enableHighAccuracy: true, maximumAge: 75000});}
    else {
      alert('GPS를 지원하지 않습니다');
    }
  }
</script>
{% endblock %}
{% block title %}Memo Edit{% endblock %}
{% block content %}
    <h1>메모 수정</h1>
   <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.text }}
        <br>
        <br>
        <label for="lat">lat : </label><input class="numbers"  type="number" step=any name="lat" id="lat"/>
	&nbsp;&nbsp;&nbsp;
	<label for="lon">lon : </label><input class="numbers"  type="number" step=any name="lon" id="lon"/><br>
        <br>
	<!--<input class="button2" type="button"  onClick = "getLocation()" value="현재위치등록" />-->
	<button class="button2" type="button" onClick="getLocation()">위치등록</button>
	&nbsp;&nbsp;&nbsp;
	<button type="submit" class="button2">수정</button>
    </form>
{% endblock %}

mysite/pmos/templates/pmos/monitor.html
{% extends 'base.html' %}
{% block title %}Room monitoring{% endblock %}
{% block content %}
<h1><a href="{% url 'home' %}">현재 방 상태</a></h1>
{% if latest_roomcond %}
      <p> 온도 : {{ latest_roomcond.temp }}°C</p>
      <p>습도 : {{ latest_roomcond.humi }}%</p>
      <p>움직임 감지 : {{ latest_roomcond.motion }}</p>
      <p>측정 시간 : {{ latest_roomcond.date | date:"Y-m-d h:i:s"}}</p>
{% else %}
  <p>No room conditions are available.</p>
{% endif %}
{% endblock %}